version: '3.8'
services:
  app:
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    restart: always
    environment:
      - WATCHPACK_POLLING=true
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"